# Generated by Django 5.1 on 2024-08-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='phno',
            field=models.IntegerField(),
        ),
    ]
