# Generated by Django 5.1 on 2024-10-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0002_alter_employeedetails_phno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='phno',
        ),
    ]
